<?php
namespace tj\sdk\test\models\merchant;

use tj\sdk\test\models\common\BaseJsonRequestDTO;

class MerchantRegisterDTO extends BaseJsonRequestDTO {
  public $name;
  public $abbr;
  public $regEmail;
  public $companyName;
  public $regNo; // company register number
  public $regAddress;
  public $country;
  public $mcc;

  public $website;
  public $contact;
  public $mobile;
  public $email; // business email

    public function rules()
    {
        return array_merge([
            [['name','abbr','regEmail','companyName','regNo','regAddress','country','mcc'],'required'],
            [['website','contact','mobile','email'],'string'],
            ['abbr','string','min'=>1,'max'=>8],
            ['regEmail','email'],
        ],parent::rules()); // TODO: Change the autogenerated stub
    }
}
