<?php
namespace app\models\emvco;


use app\models\common\BaseJsonRequestDTO;

class EmvcoGetPayloadDTO extends BaseJsonRequestDTO {
  public $type;

  public function rules()
  {
      return array_merge(
          parent::rules(),
          [
              ['type','required']
          ]
      ); // TODO: Change the autogenerated stub
  }
}
