<?php

namespace tj\sdk\test\models\enroll;


use tj\sdk\test\models\common\PayOptionsDTO;

class VerifyOrder extends PayOptionsDTO
{
    public $orderId; // your order id
    public $date; // this order generate date
    public $cardNum; // the card you will enroll or pay with
    public $phone;
    public $clientIp;
    public $transName;

    public function rules()
    {
        return array_merge(
            [
                [['orderId', 'date', 'cardNum', 'phone', 'clientIp','transName'], 'required'],
//                ['date', 'date']
            ],
            parent::rules()); // TODO: Change the autogenerated stub
    }
}
