<?php

namespace app\models\enroll;


use app\models\common\PayOptionsDTO;

class VerifyOrder extends PayOptionsDTO
{
    public $orderId; // your order id
    public $date; // this order generate date
    public $cardNum; // the card you will enroll or pay with
    public $phone;
    public $clientIp;

    public function rules()
    {
        return array_merge(
            [
                [['orderId', 'date', 'cardNum', 'phone', 'clientIp'], 'required'],
                ['date', 'date']
            ],
            parent::rules()); // TODO: Change the autogenerated stub
    }
}
