<?php
namespace app\models\config;

class paygateConfig extends baseConfig
{
    public $apiRoot = "https://paygate.uqpay.com";

    public function getRSA()
    {
        parent::getRSA();
        if ($this->testMode) {
            return $this->testRSA;
        }
        return $this->productRSA;
    }

    public function rules()
    {
        return array_merge(parent::rules(),[
            ['apiRoot','default','value'=>'https://paygate.uqpay.com']
        ]); // TODO: Change the autogenerated stub
    }
}
