<?php
namespace app\models\operation;
use yii\base\Model;

class OrderRefund extends Model {
  /**
   * is required
   */
  public $transType = 103;
  public $orderId; // your order id
  public $amount;
  public $callbackUrl; // async notice url
  public $date; // this request generate date
  public $clientType = 1;

  /**
   * not required
   */
  public $extendInfo;

  public function rules()
  {
      return [
          [['transType','orderId','amount','callbackUrl','date','clientType'],'required'],
          ['amount','number'],
          ['date','date'],
          ['transType','default', 'value'=>103],
          ['clientType','default', 'value'=>1],
      ]; // TODO: Change the autogenerated stub
  }
}
