<?php
namespace tj\sdk\test\models\operation;

/**
 * for moment is the same as order refund
 */
class OrderCancel extends OrderRefund {
    public $transType = 102;

   public function rules()
   {
       return array_merge(parent::rules(),['transType','default','value'=>102]); // TODO: Change the autogenerated stub
   }
}
