<?php

namespace tj\sdk\test\models\operation;

use yii\base\Model;

class OrderQuery extends Model
{
    /**
     * is required
     */

    public $orderId; // your order id
    public $date; // this request generate date

    public function rules()
    {
        return [
            [['orderId', 'date'], 'required']
        ]; // TODO: Change the autogenerated stub
    }

}
