<?php
namespace tj\sdk\test\models\exchangeRate;

use tj\sdk\test\models\common\BaseJsonRequestDTO;

class ExchangeRateQueryDTO extends BaseJsonRequestDTO {
  public $originalCurrency;
  public $targetCurrency;

  public function rules()
  {
      return array_merge(
          [
              [['originalCurrency','targetCurrency'],'required']
          ],
          parent::rules()); // TODO: Change the autogenerated stub
  }
}
